// lint-ai OpenClaw typed plugin (generated by `lint-ai --openclaw-install`).
//
// Thin observer: forwards lifecycle events to `lint-ai --openclaw-hook` and
// does nothing else. Capture and indexing live in the Rust binary, which is
// stateless — idempotency comes from stable document IDs in the memory store.
// Every failure path is silent (fail-open) so a broken install can never
// block OpenClaw.
import { execFileSync, spawn } from "node:child_process";

// Replaced with the absolute lint-ai binary path at install time.
const BIN = "__LINT_AI_BIN__";
// Replaced with the canonicalized project root at install time.
const INSTALL_ROOT = "__LINT_AI_ROOT__";
// Largest event payload forwarded to the binary (8 MiB, matches its stdin bound).
const MAX_PAYLOAD_BYTES = 8 * 1024 * 1024;
// Shutdown drain budget for the final flush (OpenClaw allows ~2 s total).
const SHUTDOWN_TIMEOUT_MS = 1500;

// The workspace root for a capture: prefer the event's own workspaceDir
// (multi-workspace gateways), fall back to the root baked in at install time
// (typed lifecycle events observed on a live host sometimes omit it).
function rootOf(ctx, event) {
  const root =
    ctx?.workspaceDir ?? event?.context?.workspaceDir ?? event?.workspaceDir;
  if (typeof root === "string" && root.trim()) return root.trim();
  return INSTALL_ROOT;
}

function trimEvent(event) {
  // Drop message contents for the session_end bookkeeping path; capture hooks
  // need them, so this only trims when the caller asks for it.
  return event;
}

function payloadOf(event, ctx) {
  const payload = JSON.stringify({ event: trimEvent(event), ctx: ctx ?? {} });
  if (payload.length > MAX_PAYLOAD_BYTES) {
    // Trim message bodies before giving up: keep the envelope, drop content.
    const slim = { ...event };
    if (Array.isArray(slim.messages)) {
      slim.messages = slim.messages.map((m) => ({
        role: m?.role,
        customType: m?.customType,
        details: m?.details,
      }));
    }
    return JSON.stringify({ event: slim, ctx: ctx ?? {} });
  }
  return payload;
}

// Fire-and-forget: capture must never block the agent loop.
function fire(kind, root, event, ctx) {
  if (!root) return;
  try {
    const child = spawn(BIN, ["--openclaw-hook", kind, root], {
      detached: true,
      stdio: ["pipe", "ignore", "ignore"],
    });
    child.unref();
    child.stdin.write(payloadOf(event, ctx));
    child.stdin.end();
  } catch {
    // Fail open.
  }
}

export default {
  id: "lint-ai",
  name: "Lint-AI memory",
  register(api) {
    api.on("agent_end", (event, ctx) => {
      fire("agent-end", rootOf(ctx, event), event, ctx);
    });
    api.on("before_reset", (event, ctx) => {
      fire("before-reset", rootOf(ctx, event), event, ctx);
    });
    api.on("session_start", (event, ctx) => {
      fire("session-start", rootOf(ctx, event), event, ctx);
    });
    api.on("session_end", (event, ctx) => {
      fire("session-end", rootOf(ctx, event), event, ctx);
    });
    // Compaction capture is intentionally not wired: the compaction hooks
    // were not observed on a live OpenClaw host.
    api.on("gateway_stop", (event, ctx) => {
      // Captures write through synchronously, so this is a no-op flush
      // inside the shared drain budget.
      try {
        execFileSync(BIN, ["--openclaw-hook", "shutdown", INSTALL_ROOT], {
          input: "{}",
          timeout: SHUTDOWN_TIMEOUT_MS,
        });
      } catch {
        // Bounded best-effort flush inside the shared drain budget.
      }
      void event;
      void ctx;
    });
  },
};
