#!/usr/bin/env python3
"""One-time generator: vendor spaCy stopword lists as pure-Rust static data.

Reads `spacy.lang.<lang>.stop_words.STOP_WORDS` for en/es/zh/ko, applies
per-language filtering, and emits `src/stopwords_data.rs` with four sorted,
deduped `&[&str]` arrays plus a provenance header.

This script is NOT part of the runtime. It runs once (or when upgrading
spaCy); the generated Rust file is checked in and is the only thing the
crate depends on. Runtime stopword handling stays 100% Rust.

Filtering (documented in the generated file's header):
  en: ASCII alphabetic only — drops 21 contraction fragments ("'d", "n't",
      "'ve", curly-quote variants) that our Latin tokenizer regex
      ([A-Za-z][A-Za-z0-9_-]{2,}) can never emit.
  es: alphabetic (Unicode) only — keeps accented forms ("está"); nothing
      is dropped in practice. Diacritic-folded twins are generated at
      runtime in Rust via `tokenizer::fold_diacritics`.
  zh: Han-only words (every char a CJK Unified Ideograph) of any length —
      drops 288 punctuation/symbol/digit entries ("④", "＜±", "3", "...").
      Two-char words match our Han bigram tokens directly; single chars
      match unigram tokens.
  ko: Hangul-syllable-only words — nothing is dropped in practice.

Usage:
    python3 scripts/gen_stopwords_data.py [--out src/stopwords_data.rs]
"""

import argparse
import datetime
import unicodedata
from pathlib import Path


def is_han(ch: str) -> bool:
    try:
        return "CJK UNIFIED IDEOGRAPH" in unicodedata.name(ch)
    except ValueError:
        return False


def is_hangul_syllable(ch: str) -> bool:
    try:
        return "HANGUL SYLLABLE" in unicodedata.name(ch)
    except ValueError:
        return False


def load_lists():
    import spacy
    from spacy.lang.en.stop_words import STOP_WORDS as EN
    from spacy.lang.es.stop_words import STOP_WORDS as ES
    from spacy.lang.ko.stop_words import STOP_WORDS as KO
    from spacy.lang.zh.stop_words import STOP_WORDS as ZH

    en = sorted({w for w in EN if w.isascii() and w.isalpha()})
    es = sorted({w for w in ES if w.isalpha()})
    zh = sorted({w for w in ZH if w and all(is_han(c) for c in w)})
    ko = sorted({w for w in KO if w and all(is_hangul_syllable(c) for c in w)})
    return spacy.__version__, {"en": en, "es": es, "zh": zh, "ko": ko}


def emit_rust(spacy_version: str, lists: dict) -> str:
    date = datetime.date.today().isoformat()
    lines = [
        "// GENERATED by scripts/gen_stopwords_data.py — DO NOT EDIT.",
        "// Regenerate with: python3 scripts/gen_stopwords_data.py",
        "//",
        "// Provenance:",
        f"//   spaCy {spacy_version} `spacy.lang.<en|es|zh|ko>.stop_words.STOP_WORDS`",
        "//   (MIT license), generated " + date + ".",
        "// Filtering: en = ASCII alpha only (drops contraction fragments like",
        "//   \"'d\"/\"n't\" that the Latin tokenizer regex can never emit);",
        "//   es = alphabetic incl. accents (diacritic-folded twins are derived",
        "//   at runtime via `crate::tokenizer::fold_diacritics`);",
        "//   zh = Han-only words of any length (drops punctuation/symbols/digits);",
        "//   ko = Hangul-syllable-only words. All arrays sorted and deduped.",
        "//",
        "// Vendored word data only — no spaCy/Python at runtime.",
        "",
    ]
    for lang, words in lists.items():
        lines.append(f"/// spaCy {spacy_version} stopwords for `{lang}` (see header).")
        lines.append(
            f"pub(crate) static STOPWORDS_{lang.upper()}: &[&str] = &["
        )
        for w in words:
            escaped = w.replace("\\", "\\\\").replace('"', '\\"')
            lines.append(f'    "{escaped}",')
        lines.append("];")
        lines.append("")
    return "\n".join(lines)


def main() -> None:
    ap = argparse.ArgumentParser()
    ap.add_argument("--out", default="src/stopwords_data.rs")
    args = ap.parse_args()
    version, lists = load_lists()
    for lang, words in lists.items():
        print(f"{lang}: {len(words)} words")
    out = Path(args.out)
    out.write_text(emit_rust(version, lists), encoding="utf-8")
    print(f"wrote {out}")


if __name__ == "__main__":
    main()
