// lint-ai OpenClaw internal hook (generated by `lint-ai --openclaw-install`).
//
// Thin in-process HTTP client. Hook policy stays in the Lint-AI server.
// Every failure path returns without touching the event (fail-open), so a
// broken install can never block OpenClaw.
// Replaced with the canonicalized project root at install time: the fallback
// workspace when the bootstrap event carries none (typed lifecycle events
// observed on a live host sometimes omit workspaceDir entirely).
const INSTALL_ROOT = "__LINT_AI_ROOT__";
// How long the recall query may block a turn before we give up (fail-open).
const TIMEOUT_MS = Number(process.env.LINT_AI_OPENCLAW_HOOK_TIMEOUT_MS ?? 8000);
const SERVER_URL = (process.env.LINTAI_SERVER_URL ?? "http://127.0.0.1:8080").replace(/\/$/, "");
const SERVER_TOKEN = process.env.LINTAI_SERVER_TOKEN ?? "";
// Last user text per session, correlated from `message:received` (the
// `agent:bootstrap` event itself usually carries no user message).
const lastUserText = new Map();

function trimEvent(event) {
  // The bootstrap event carries bootstrap file contents; the Rust side only
  // needs the file list shape plus context. Drop file contents to keep the
  // pipe small (the binary re-attaches files verbatim from the live event).
  const { bootstrapFiles, ...restContext } = event.context ?? {};
  const files = Array.isArray(bootstrapFiles)
    ? bootstrapFiles.map((f) => ({ name: f?.name, path: f?.path, missing: f?.missing }))
    : [];
  return {
    type: event.type,
    action: event.action,
    sessionKey: event.sessionKey,
    timestamp: event.timestamp,
    context: { ...restContext, bootstrapFiles: files },
  };
}

function userTextFromMessage(event) {
  const msg = event.message ?? event.payload?.message ?? event;
  const content = msg.content ?? msg.text ?? "";
  if (typeof content === "string" && content.trim()) return content.trim();
  if (Array.isArray(content)) {
    const text = content
      .filter((b) => b && (b.type === "text" || typeof b.text === "string"))
      .map((b) => b.text ?? "")
      .join("\n")
      .trim();
    if (text) return text;
  }
  return "";
}

export default async function lintAiHook(event) {
  try {
    if (event?.type === "message" && event?.action === "received") {
      const text = userTextFromMessage(event);
      if (text && event.sessionKey) {
        lastUserText.set(event.sessionKey, text);
        // Bounded correlation cache; bootstrap consumes it on the next turn.
        if (lastUserText.size > 1000) {
          const oldest = lastUserText.keys().next().value;
          lastUserText.delete(oldest);
        }
      }
      return;
    }

    if (event?.type === "agent" && event?.action === "bootstrap") {
      const trimmed = trimEvent(event);
      // Prefer the event's own workspace; fall back to the install-time root.
      // The fallback is written back into the trimmed context so the binary
      // sees one consistent root (it also builds the injected file path from it).
      const workspaceDir =
        typeof trimmed.context?.workspaceDir === "string" && trimmed.context.workspaceDir.trim()
          ? trimmed.context.workspaceDir
          : INSTALL_ROOT;
      trimmed.context = { ...trimmed.context, workspaceDir };
      const payload = {
        event: trimmed,
        query: lastUserText.get(event.sessionKey) ?? "",
      };
      const controller = new AbortController();
      const timeout = setTimeout(() => controller.abort(), TIMEOUT_MS);
      let result;
      try {
        const response = await fetch(`${SERVER_URL}/integrations/openclaw/hooks/bootstrap`, {
          method: "POST",
          headers: { "content-type": "application/json", ...(SERVER_TOKEN ? { authorization: `Bearer ${SERVER_TOKEN}` } : {}) },
          body: JSON.stringify(payload),
          signal: controller.signal,
        });
        if (!response.ok) return;
        result = await response.json();
      } finally {
        clearTimeout(timeout);
      }
      if (result && Array.isArray(result.bootstrapFiles)) {
        // Re-attach untouched file contents for entries the binary passed
        // through; the injected LINTAI.md entry arrives complete.
        const byName = new Map(
          (event.context.bootstrapFiles ?? []).map((f) => [f?.name, f]),
        );
        event.context.bootstrapFiles = result.bootstrapFiles.map((f) => {
          const original = f?.name ? byName.get(f.name) : undefined;
          return original && f.name !== "LINTAI.md" ? { ...original } : f;
        });
      }
    }
  } catch {
    // Fail open: leave the event untouched.
  }
}
