// lint-ai OpenClaw internal hook (generated by `lint-ai --openclaw-install`).
//
// Thin in-process wrapper around `lint-ai --openclaw-hook`. All logic lives in
// the Rust binary; this file only serializes the event, spawns the binary
// synchronously, and applies the returned mutations to the live event object.
// Every failure path returns without touching the event (fail-open), so a
// broken install can never block OpenClaw.
import { execFileSync } from "node:child_process";

// Replaced with the absolute lint-ai binary path at install time.
const BIN = "__LINT_AI_BIN__";
// How long the recall query may block a turn before we give up (fail-open).
const TIMEOUT_MS = Number(process.env.LINT_AI_OPENCLAW_HOOK_TIMEOUT_MS ?? 8000);
// Last user text per session, correlated from `message:received` (the
// `agent:bootstrap` event itself usually carries no user message).
const lastUserText = new Map();

function trimEvent(event) {
  // The bootstrap event carries bootstrap file contents; the Rust side only
  // needs the file list shape plus context. Drop file contents to keep the
  // pipe small (the binary re-attaches files verbatim from the live event).
  const { bootstrapFiles, ...restContext } = event.context ?? {};
  const files = Array.isArray(bootstrapFiles)
    ? bootstrapFiles.map((f) => ({ name: f?.name, path: f?.path, missing: f?.missing }))
    : [];
  return {
    type: event.type,
    action: event.action,
    sessionKey: event.sessionKey,
    timestamp: event.timestamp,
    context: { ...restContext, bootstrapFiles: files },
  };
}

function userTextFromMessage(event) {
  const msg = event.message ?? event.payload?.message ?? event;
  const content = msg.content ?? msg.text ?? "";
  if (typeof content === "string" && content.trim()) return content.trim();
  if (Array.isArray(content)) {
    const text = content
      .filter((b) => b && (b.type === "text" || typeof b.text === "string"))
      .map((b) => b.text ?? "")
      .join("\n")
      .trim();
    if (text) return text;
  }
  return "";
}

export default function lintAiHook(event) {
  try {
    if (event?.type === "message" && event?.action === "received") {
      const text = userTextFromMessage(event);
      if (text && event.sessionKey) {
        lastUserText.set(event.sessionKey, text);
        // Bounded correlation cache; bootstrap consumes it on the next turn.
        if (lastUserText.size > 1000) {
          const oldest = lastUserText.keys().next().value;
          lastUserText.delete(oldest);
        }
      }
      return;
    }

    if (event?.type === "agent" && event?.action === "bootstrap") {
      const workspaceDir = event.context?.workspaceDir;
      if (!workspaceDir) return;
      const payload = {
        event: trimEvent(event),
        query: lastUserText.get(event.sessionKey) ?? "",
      };
      const stdout = execFileSync(
        BIN,
        ["--openclaw-hook", "bootstrap", workspaceDir],
        {
          input: JSON.stringify(payload),
          timeout: TIMEOUT_MS,
          maxBuffer: 8 * 1024 * 1024,
          encoding: "utf8",
        },
      );
      const result = JSON.parse(String(stdout));
      if (result && Array.isArray(result.bootstrapFiles)) {
        // Re-attach untouched file contents for entries the binary passed
        // through; the injected LINTAI.md entry arrives complete.
        const byName = new Map(
          (event.context.bootstrapFiles ?? []).map((f) => [f?.name, f]),
        );
        event.context.bootstrapFiles = result.bootstrapFiles.map((f) => {
          const original = f?.name ? byName.get(f.name) : undefined;
          return original && f.name !== "LINTAI.md" ? { ...original } : f;
        });
      }
    }
  } catch {
    // Fail open: leave the event untouched.
  }
}
